---
-
  hosts: ci-server
  roles:
    - geerlingguy.jenkins
    - geerlingguy.git
  sudo: true
  vars:
    jenkins_hostname: localhost
    git_install_from_source: false
    git_version: 2.4.9
    git_packages:
      - git
